### ISSUE TITLE
HTML Forms Needed

### ISSUE THREAD

**Issue by FadiZahhar** [FadiZahhar/servicesapp#2]
Hi @Vikingwalk 

thank you for your efforts,
the forms you shared are amazing good efforts.

since we will need more forms on later satage for the app, it is a good idea to prepare them as html like you did.

I need more the following forms that you can practice on them and add them on same structure at the public html[
](https://www.w3schools.com/howto/howto_css_checkout_form.asp)
[
](https://www.w3schools.com/howto/howto_css_contact_form.asp)

https://www.w3schools.com/howto/howto_css_social_login.asp

@MohamadAssy  and @mohamadchams123  you may help on this task as well.

in case you want to help please communicate here on this ticket so @Vikingwalk  knows and to split the tasks in between. Thank you.

**Comment by FadiZahhar** [comment]
this is a contact form is needed also
https://www.w3schools.com/howto/howto_css_contact_form.asp

also  check out form 

https://www.w3schools.com/howto/howto_css_checkout_form.asp

thank you in advance.

**Comment by mohamadchams123** [comment]
hi
i'm facing internet issues
I'll jump back into it once it gets fixed

**Comment by Vikingwalk** [comment]
hello i did them all
